-- noqa: disable=LT05
SET LOCAL statement_timeout = '5s' ;
SET LOCAL lock_timeout = '1s' ;

CREATE TABLE IF NOT EXISTS public.locations (
id smallint PRIMARY KEY,
city text NOT NULL,
state text NOT NULL,
lat real NOT NULL,
lng real NOT NULL
) ;

CREATE TABLE IF NOT EXISTS public.wetbulb (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
location_id smallint NOT NULL,
date date NOT NULL,
wetbulb real NOT NULL,
wetbulb_avg real,
source text NOT NULL DEFAULT 'isd',
station_id text,
station_distance_km real,
station_elevation_difference_m real,
observed_hours smallint,
station_quality text,
reference_station_id text,
homogenization_method text,
homogenization_overlap_days integer,
wetbulb_adjustment real,
wetbulb_avg_adjustment real,
CONSTRAINT wetbulb_source_check CHECK (source IN ('eccc', 'ghcnh', 'isd', 'nldas', 'lcd', 'giovanni', 'era5land')),
CONSTRAINT wetbulb_station_quality_check CHECK (station_quality IS NULL OR station_quality IN ('complete', 'sparse')),
CONSTRAINT wetbulb_homogenization_method_check CHECK (homogenization_method IS NULL OR homogenization_method IN ('reference', 'monthly_overlap', 'global_overlap'))
) ;

CREATE UNIQUE INDEX IF NOT EXISTS wetbulb_location_date_uidx
ON public.wetbulb (location_id, date) ;

CREATE TABLE IF NOT EXISTS public.gmst_observations (
year smallint PRIMARY KEY,
anomaly double precision NOT NULL,
anomaly_lo double precision NOT NULL,
anomaly_hi double precision NOT NULL,
source_version text NOT NULL
) ;

CREATE TABLE IF NOT EXISTS public.gmst_scenarios (
scenario text NOT NULL,
year smallint NOT NULL,
anomaly double precision NOT NULL,
anomaly_lo double precision NOT NULL,
anomaly_hi double precision NOT NULL,
sigma_g double precision NOT NULL,
PRIMARY KEY (scenario, year),
CONSTRAINT gmst_scenario_check CHECK (scenario IN ('ssp126', 'ssp245', 'ssp370'))
) ;

CREATE TABLE IF NOT EXISTS public.forecast_station_groups (
location_id smallint PRIMARY KEY,
station_group text NOT NULL
) ;

CREATE TABLE IF NOT EXISTS public.forecast_interval_calibration (
metric text PRIMARY KEY,
calibration_factor double precision NOT NULL CHECK (NOT calibration_factor < 1.0)
) ;
