-- noqa: disable=LT05
-- squawk-ignore-file prefer-bigint-over-smallint,changing-column-type,prefer-robust-stmts,require-concurrent-index-creation
-- noqa: enable=LT05

-- SET LOCAL keeps these timeouts scoped to the executing transaction so they
-- never leak into later COPY/DELETE/ANALYZE statements on the same connection.
SET LOCAL statement_timeout = '5s' ;
SET LOCAL lock_timeout = '1s' ;
DROP MATERIALIZED VIEW IF EXISTS public.pet_year_avg CASCADE ;
DROP MATERIALIZED VIEW IF EXISTS public.pet_year_max CASCADE ;


CREATE TABLE IF NOT EXISTS public.locations (
id smallint PRIMARY KEY,
city text NOT NULL,
state text NOT NULL,
lat real NOT NULL,
lng real NOT NULL
) ;

DO $$
DECLARE
    public_schema constant text := 'public' ;
    pet_year_relation_kind "char" ;
    forecast_relation_kind "char" ;
BEGIN
    SELECT
        c.relkind
    INTO pet_year_relation_kind
    FROM pg_catalog.pg_class AS c
    JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
    WHERE n.nspname = public_schema
    AND c.relname = 'pet_year' ;

    IF pet_year_relation_kind = 'm' THEN
        EXECUTE format('DROP MATERIALIZED VIEW %I.pet_year CASCADE', public_schema) ;
    ELSIF pet_year_relation_kind = 'v' THEN
        EXECUTE format('DROP VIEW %I.pet_year CASCADE', public_schema) ;
    END IF ;

    IF EXISTS (
        SELECT
            1
        FROM information_schema.columns
        WHERE table_schema = public_schema
        AND table_name = 'locations'
        AND column_name = 'location_id'
    )
    AND NOT EXISTS (
        SELECT
            1
        FROM information_schema.columns
        WHERE table_schema = public_schema
        AND table_name = 'locations'
        AND column_name = 'id'
    ) THEN
        ALTER TABLE public.locations RENAME COLUMN location_id TO id ;
    END IF ;

    -- Legacy type migration, guarded so it only runs when a column still has
    -- the old type: an unconditional ALTER TYPE fails whenever views exist,
    -- and schema-ensuring runs must not require dropping views first.
    IF EXISTS (
        SELECT
            1
        FROM information_schema.columns
        WHERE table_schema = public_schema
        AND table_name = 'locations'
        AND (
            (column_name = 'id' AND data_type != 'smallint')
            OR (column_name = 'lat' AND data_type != 'real')
            OR (column_name = 'lng' AND data_type != 'real')
        )
    ) THEN
        ALTER TABLE public.locations
        ALTER COLUMN id TYPE smallint USING id::smallint,
        ALTER COLUMN lat TYPE real USING lat::real,
        ALTER COLUMN lng TYPE real USING lng::real ;
    END IF ;

    CREATE TABLE IF NOT EXISTS public.pet (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        location_id smallint NOT NULL,
        date date NOT NULL,
        pet real NOT NULL
    ) ;

    -- Same guarded legacy type migration for the pet table.
    IF EXISTS (
        SELECT
            1
        FROM information_schema.columns
        WHERE table_schema = public_schema
        AND table_name = 'pet'
        AND (
            (column_name = 'id' AND data_type != 'integer')
            OR (column_name = 'location_id' AND data_type != 'smallint')
            OR (column_name = 'pet' AND data_type != 'real')
        )
    ) THEN
        ALTER TABLE public.pet
        ALTER COLUMN id TYPE integer USING id::integer,
        ALTER COLUMN location_id TYPE smallint USING location_id::smallint,
        ALTER COLUMN pet TYPE real USING pet::real ;
    END IF ;

    IF EXISTS (
        SELECT
            1
        FROM pg_catalog.pg_class AS i
        JOIN pg_catalog.pg_index AS ix ON ix.indexrelid = i.oid
        JOIN pg_catalog.pg_class AS t ON t.oid = ix.indrelid
        JOIN pg_catalog.pg_namespace AS n ON n.oid = i.relnamespace
        WHERE n.nspname = public_schema
        AND i.relname = 'id'
        AND t.relname = 'pet'
    ) THEN
        DROP INDEX public.id ;
    END IF ;

    SELECT
        c.relkind
    INTO forecast_relation_kind
    FROM pg_catalog.pg_class AS c
    JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
    WHERE n.nspname = public_schema
    AND c.relname = 'pet_forecast' ;

    IF forecast_relation_kind IN ('r', 'p') THEN
        IF to_regclass('public.pet_forecast_legacy') IS NULL THEN
            ALTER TABLE public.pet_forecast RENAME TO pet_forecast_legacy ;
        ELSE
            DROP TABLE public.pet_forecast CASCADE ;
        END IF ;
    END IF ;
END $$ ;

CREATE TABLE IF NOT EXISTS public.wetbulb (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
location_id smallint NOT NULL,
date date NOT NULL,
wetbulb real NOT NULL
) ;

-- wetbulb_avg is nullable: rows loaded before the NLDAS-2 switch only have
-- the ERA5/Stull daily max and have no daily average value.
ALTER TABLE public.wetbulb ADD COLUMN IF NOT EXISTS wetbulb_avg real ;

-- One-time migrations: the covering indexes become UNIQUE so loads can upsert
-- with ON CONFLICT (location_id, date). Dedupe first (keep the most recently
-- inserted row). The timeout is lifted with separate top-level statements
-- because statement_timeout is armed when a statement starts - a SET LOCAL
-- inside a DO block cannot extend the timeout of that same block.
SET LOCAL statement_timeout = '0' ;
SET LOCAL lock_timeout = '0' ;

DO $$
BEGIN
    IF to_regclass('public.pet') IS NOT NULL
    AND to_regclass('public.pet_location_date_uidx') IS NULL THEN
        DELETE FROM public.pet AS a
        USING public.pet AS b
        WHERE a.location_id = b.location_id
        AND a.date = b.date
        AND a.id < b.id ;
        DROP INDEX IF EXISTS pet_location_date_covering_idx ;
        CREATE UNIQUE INDEX pet_location_date_uidx
        ON public.pet (location_id, date)
        INCLUDE (pet) ;
    END IF ;
END $$ ;

DO $$
BEGIN
    IF to_regclass('public.wetbulb_location_date_uidx') IS NULL THEN
        DELETE FROM public.wetbulb AS a
        USING public.wetbulb AS b
        WHERE a.location_id = b.location_id
        AND a.date = b.date
        AND a.id < b.id ;
        DROP INDEX IF EXISTS wetbulb_location_date_covering_idx ;
        CREATE UNIQUE INDEX wetbulb_location_date_uidx
        ON public.wetbulb (location_id, date)
        INCLUDE (wetbulb) ;
    END IF ;
END $$ ;
