AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for wet-bulb data pipeline (S3 bucket)

Parameters:
  BucketName:
    Type: String
    Default: wetbulb-parquet-files
    Description: Name of the S3 bucket (Must be globally unique)

Resources:
  WetbulbParquetFilesAccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-access-logs"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  WetbulbParquetFilesAccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WetbulbParquetFilesAccessLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3ServerAccessLogsDelivery
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${WetbulbParquetFilesAccessLogsBucket.Arn}/s3-access-logs/*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:s3:::${BucketName}"
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !GetAtt WetbulbParquetFilesAccessLogsBucket.Arn
              - !Sub "${WetbulbParquetFilesAccessLogsBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

  WetbulbParquetFilesBucket: # NOSONAR
    Type: AWS::S3::Bucket # NOSONAR
    DependsOn: WetbulbParquetFilesAccessLogsBucketPolicy
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref WetbulbParquetFilesAccessLogsBucket
        LogFilePrefix: s3-access-logs/

  WetbulbParquetFilesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WetbulbParquetFilesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !GetAtt WetbulbParquetFilesBucket.Arn
              - !Sub "${WetbulbParquetFilesBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

Outputs:
  BucketName:
    Value: !Ref WetbulbParquetFilesBucket
    Description: The name of the S3 Bucket
  AccessLogsBucketName:
    Value: !Ref WetbulbParquetFilesAccessLogsBucket
    Description: The name of the S3 bucket receiving server access logs
