"""
This type stub file was generated by pyright.
"""

import pytest
import sys

"""
This type stub file was generated by pyright.
"""
groups = ...
defaults = ...
if sys.platform == "emscripten":
    ...
if sys.platform == "win32":
    ...
else:
    ...
if sys.platform == "win32":
    ...
else:
    ...
def pytest_ignore_collect(collection_path, config):
    ...

@pytest.fixture(autouse=True)
def add_fs(doctest_namespace, request, tmp_path):
    ...

@pytest.fixture(scope="session")
def unary_func_fixture():
    """
    Register a unary scalar function.
    """
    ...

@pytest.fixture(scope="session")
def unary_agg_func_fixture():
    """
    Register a unary aggregate function (mean)
    """
    ...

@pytest.fixture(scope="session")
def varargs_agg_func_fixture():
    """
    Register a unary aggregate function
    """
    ...

