"""
This type stub file was generated by pyright.
"""

from typing import Any

class WriteOptions:
    def __init__(
        self,
        *,
        include_header: bool = ...,
        batch_size: int = ...,
        delimiter: str = ...,
        quoting_style: str = ...,
    ) -> None: ...

def write_csv(
    data: Any,
    output_file: Any,
    write_options: WriteOptions | None = ...,
    memory_pool: Any = ...,
) -> None: ...
